### ISSUE TITLE
Request for `firamath-otf` package.

### ISSUE THREAD

**Issue by jpgoldberg** [tectonic-typesetting/tectonic-staging#13]
The firamath-otf package is missing from the bundle.

Note that I have not yet tested whether this package works and behaves correctly and copied to the local directory (which isn't a great solution for me any way, but I will try at least for testing).

**Comment by pkgw** [comment]
I will see if I can address this in the course of dealing with #9 (that is, upgrading to TexLive 2020).

Thank you for your patience and for filing your issue reports!

**Comment by Neved4** [comment]
ping @jpgoldberg

**Comment by pkgw** [comment]
Hopefully if this works in one place it should work in general, so I'm going to go ahead and close this report based on @mnrvwl's followup. If @jpgoldberg or anyone else finds that there is still an issue with the 2021 or 2022 bundles, please comment here or file a new issue.
