### ISSUE TITLE
package marginnote not working correctly

### ISSUE THREAD

**Issue by amybruno** [tectonic-typesetting/tectonic-staging#3]
Using the package `marginnote` with tectonic produces strange results. In the following MWE, the intended result is for 'Note' to appear in the right margin, but in the current version of tectonic, nothing shows up in the right margin.

```
\documentclass{article}
\usepackage{marginnote}
\begin{document}
\marginnote{Note}
Main text.
\end{document}
```

I have also found other strange behaviour. In a more complicated document that I'm editing, margin-notes show up, but not in the margin where they're intended to be

**Comment by chr-br** [comment]
I should also mention that latex produces no warnings or errors when tectonic compiles the example I gave.

**Comment by pkgw** [comment]
I apologize for never responding to this issue — posted almost exactly a year ago! Someone else posted [an issue in the main repository](https://github.com/tectonic-typesetting/tectonic/issues/182) about the same package. The issue tracker for the main project is a better place to discuss this topic, so please subscribe to that issue if you're interested in following progress toward solving it.
