### ISSUE TITLE
Add the emerald package to the bundle

### ISSUE THREAD

**Issue by ocefpaf** [tectonic-typesetting/tectonic-staging#4]
If tectonic-staging accepts package requests please add https://ctan.org/pkg/emerald?lang=en to the bundle. If not, please just close this.

PS: thanks for the awesome package!

**Comment by pkgw** [comment]
After much time has passed ... It seems that Emerald isn't contained in TeXLive, for some reason. The way the system is set up it would be difficult to incorporate it right now. Do you happen to know why it might be available in MikTeX but not TeXLive?

**Comment by pkgw** [comment]
As far as I can tell, this remains true. Closing since there doesn't seem to have been strong interest.
