### ISSUE TITLE
Add the package "expex" to the bundle

### ISSUE THREAD

**Issue by patrl** [tectonic-typesetting/tectonic-staging#5]
I'd very much appreciate it if you could add the package [expex](https://ctan.org/pkg/expex?lang=en) to the bundle. It's the most full-featured and actively-maintained package for linguistic examples and thus sorely missed!

**Comment by pkgw** [comment]
Thanks for reporting! Please ping me aggressively if I don't get on this soon — it's easy to do, but I have a lot of distractions these days so I might lose track of this.

**Comment by patrl** [comment]
Do you accept pull requests? I'm still figuring out how this code base works, but AFAIK this is as simple as adding "collection-humanities" to the list of collections in `staging.sh`.

**Comment by pkgw** [comment]
PRs are encouraged! Due to the nature of this repo, I expect that it will be tricky for you to test any proposed changes yourself, but your stated approach sounds right to me. So if you can submit a PR with that change, I am happy to double-check it and go from there.

**Comment by pkgw** [comment]
Apologies for the absolutely enormous wait! I am testing a new version of the bundle based on TeXLive 2018.1 that should now include this package. If you install the latest release (version 0.1.9), you should be able to test it out by running Tectonic with the argument `-w https://newton.cx/~peter/files/tlextras-2018.1dev.tar`. E.g.:

```
tectonic -w https://newton.cx/~peter/files/tlextras-2018.1dev.tar mydoc.tex
```

I'm able to `\usepackage{expex}`, but it would be great if you could give it a whirl and see if it works!

**Comment by pkgw** [comment]
This was fixed!
