### ISSUE TITLE
Sync with TeX Live 2018

### ISSUE THREAD

**Issue by l2dy** [tectonic-typesetting/tectonic-staging#7]
The default bundle is currently 2016.0r4. Please update to the current version.

**Comment by pkgw** [comment]
Yes, I am working towards this. The recent PR tectonic-typesetting/tectonic#181 makes it (again) possible to use alternate bundles via the command line, which will help in testing the new version before rolling it out as the new default.

**Comment by l2dy** [comment]
Any progress?

**Comment by pkgw** [comment]
No, I am afraid not — real life has been intervening. If you are feeling adventurous, you could try using the system in the [staging repository](https://github.com/tectonic-typesetting/tectonic-staging) to build your own updated bundle, but the process is not well described so I will understand if that is too much of a hassle.

**Comment by pkgw** [comment]
I am now testing this! Try installing Tectonic version 0.1.9 and running with the following `-w` argument:

```
tectonic -w https://newton.cx/~peter/files/tlextras-2018.1dev.tar mydoc.tex
```

**Comment by l2dy** [comment]
Thanks! The new bundle works for me.

**Comment by l2dy** [comment]
Now that https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar is up, is this issue fixed?

**Comment by pkgw** [comment]
Yes, I'd say it is, and so (I assume this is your implication) I'll go ahead and close it.
